### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by jacquelinekay** [JenniferBuehler/jb-ros-packs#10]
You mentioned GraspIt is having some issues with contacts so it's hard to test it right now, but you could write unit tests to automate checking the validity of your code without relying on GraspIt to work. For example, a lot of the math helper functions could be tested.

**Comment by JenniferBuehler** [comment]
Yes, unit tests are always a good idea. I did test my code though -- admittedly with printf and manual debugging though. I don't think the issue is with the outputted formats. GraspIt also crashes with its own hand contact points (e.g. DLR hand).

I'll valgrind the whole process over the weekend, I think it should not be too hard to find the problem. I'm suspecting it's something with updated system libraries, because that issue did not happen when I was using an older ubuntu dist (which I now don't have any more). The patch that needed to be applied to the GraspIt code is also new.

I'll add unit tests to the project at some stage in the near future.

**Comment by JenniferBuehler** [comment]
The problem is with the Qt libraries which have probably been updated since last time I've used GraspIt. The GUI corrupts the memory and fscanf() calls fail when reading the contacts file.
I have posted a bug report and will see what the feedback on this is over the next days.

I will re-open this one as a new issue.
