### ISSUE TITLE
License and external included code

### ISSUE THREAD

**Issue by jacquelinekay** [JenniferBuehler/jb-ros-packs#11]
This is something we can discuss more offline, but for any open source project it's good to consider the license. At OSRF we actually copy the copyright statement/shortened license in every file in our repositories. I noticed the license is GPL right now. I would also suggest we come up with another scheme for connecting to the jaco_arm and inventor_viewer packages, since those are heavily based on other people's code (maybe jaco_arm could be a separate repo that is your fork of the existing package?)

**Comment by JenniferBuehler** [comment]
I haven't copied the license statement into the files yet, because I thought it's enough to have it in the main folder. This can be changed of course.

jaco_arm is actually only my code. There has been a previous urdf model (I put it in the docs folder for reference), but the current model has not much of this one. Over time I redesigned the model because none of the available URDF models mirrored the actual robot accurately enough for the purposes of my experiments.
But I agree, the binding to the inventor_viewer and ivcon packages can be improved. I think there's also a new/different version of ivcon in the meantime which may be worth looking at.
