### ISSUE TITLE
[grasp_planning_graspit] copy/paste line for installing dependencies

### ISSUE THREAD

**Issue by jacquelinekay** [JenniferBuehler/jb-ros-packs#14]
There were two I had to install for this package that aren't in the core ros-comm stack, e.g.

`sudo apt-get install ros-indigo-eigen-conversions ros-indigo-roslint`

consider adding this to the install instructions.

Also, if `grasp_planning_graspit` is supposed to be ros-independent, why does it declare a dependency on roscpp and std_msgs in package.xml?

**Comment by JenniferBuehler** [comment]
It actually is mentioned in the README. But as discussed in a separate thread, install instructions will be moved to Wiki anyway, then can be improved.

As to the ROS dependencies: I was just going to remove them today. I haven't looked at the cmake stuff since I made it work back in December. Definitely needs a cleanup.

Nice spotting the roscpp and std_msgs leftover dependency, definitely obsolete (at first, the package was mixed with grasp_planning_graspit_ros so that's still old remnants)

**Comment by JenniferBuehler** [comment]
Install instructions updated. They are still in the README.md and will be moved to Wiki (or other documentation location) in the next days.
