### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jacquelinekay** [JenniferBuehler/jb-ros-packs#15]
This is a bit of a matter of taste, but when using Doxygen I generally prefer to have a compact script that generates the documentation instead of committing all of the html files to the repository. It makes the process more involved for someone who checks out the repository, but it saves a bit of space. It also makes the diffs smaller when the documentation is changed.

Smaller issues with documentation:
- The Copyright seems to get intermixed with the Doxygen documentation in places.
- External links from within the generated html seem to be broken.

**Comment by JenniferBuehler** [comment]
Yes I agree, I thought about that. But it's nice also if people looking at the repo can look at the API already before cloning and making the package.

Thanks for spotting issues with documentation, will look at it asap.

**Comment by JenniferBuehler** [comment]
- Fixed issue with Copyright in doxygen.
- Broken links were due to the includion of the README.md (formatted used for display in github) as doxygen MAIN page. Changed this now.

I will leave the API files in there for now. When the package is finished, and has its own place for documentation, I will maintain a recent version of generated doxygen files there. Will add this as issue so it can be tracked.
