### ISSUE TITLE
Pointers, pointer types, references

### ISSUE THREAD

**Issue by jacquelinekay** [JenniferBuehler/jb-ros-packs#4]
https://github.com/JenniferBuehler/jb-ros-packs/blob/master/urdf2graspit/include/urdf2graspit/Urdf2Graspit.h#L112

Is there a better type you could use than a `double*` for "frictionEdges"? For example, an Eigen 6-vector.

Make sure that potentially large objects (e.g. vectors) are passed to functions by reference or, if possible, const references. You do this in most places, but for example the reference is missing on line 160 of the above file.

There's also a few places where you pass a `const std::string *` instead of a reference to a const std::string. I haven't looked at the body of this function yet, but is that intentional?

**Comment by JenniferBuehler** [comment]
The double* pointer is because I've used this in a function which I copied from the GraspIt code (setUpFrictionEllipsoid in urdf2graspit.cpp), which used the double pointer. I know it isn't pretty, I just haven't done an extra conversion yet before calling the GraspIt function. Will add this.

Thanks for pointing out the missing reference in line 160. This was a mistake and it's now fixed.

The string pointer is because it is an optional argument, so you can pass NULL instead of a string to skip the functionality. I preferred this over passing an extra boolean to switch on/off the functionality.

**Comment by JenniferBuehler** [comment]
I changed the double pointer for frictionEdges.

I left the string pointer parameters as they were for now until decided whether to leave it as is, or add an extra bool parameter to skip the option.
