### ISSUE TITLE
Does urdf2graspit.cpp need to be a ROS node?

### ISSUE THREAD

**Issue by jacquelinekay** [JenniferBuehler/jb-ros-packs#9]
You do not publish/subscribe from the main function, so I was wondering if it's even necessary to call `ros::init` (which initializes the process as a node).

**Comment by JenniferBuehler** [comment]
Hm, that's because I wanted to use it via rosrun. But yes, it's not really necessary at this stage I guess.

**Comment by jacquelinekay** [comment]
You could go either way (or both ways) in the direction of more or less ROS integration. For example, you could write a ROS service that uses the urdf2graspit API to take the `robot_description` ROS parameter and convert it to GraspIt format. Or a ROS node that republishes it to a topic. You could also take the `urdf2graspit` file, separate out the main function, and compile the `urdf2graspit` class as a shared library. It all depends on how you want people to use it.

**Comment by JenniferBuehler** [comment]
Yes, it's the plan to integrate a ROS service to do the conversion. The option to use the ``robot_description`` is a great idea! 
I was thinking to create a message type which contains the resulting XML files as strings. This can be returned by the service. Then another node (or the end user) can write the stuff to files as seen fit. This would also separate out all the file i/o from the main code.

I have kept the main API (Urdf2GraspIt.h) independent of ROS (apart from the ROS_* printing) and I'd prefer to keep it this way. I had the same idea with the library & a ros node wrapper.

Will do this soon and close the issue as soon as it's done.

**Comment by JenniferBuehler** [comment]
I have separated out all the file writing operations, so now it will be very easy to create a ROS service. The main interface only returns strings (the contents of inventor and XML files) which can be passed on as a message and then written to disk in a separate step.

I also made a library and singled out the ROS node into one .cpp file.

I have also provided a launch file template (and an example with the jaco hand) so that running urdf2graspit is now easy, and parameters can be changed quickly in the launch file.

The service itself will be added soon, but it is not of high priority right now as it's not yet needed anywhere.
